### ISSUE TITLE
Chunks not loaded when owner offline

### ISSUE THREAD

**Issue by Teibidh** [gigabit101/SimpleChunkLoader#1]
I play using a non-op account. Thus far I cannot validate that the blocks are working when I am connected, though I believe that they are, I can state with a certainty that they are not working when I am not logged in.

While I know that this is a common issue for this type of mod the others that I have worked with in the past have overcome this issue, and for me it's almost a requirement. I generally only get an hour or so a day to play, but I enjoy working with complex harvesting/assembly lines using EnderIO and other mods, having to be logged on for these things to do their jobs is ... painful.

**Comment by gigabit101** [comment]
So first of all if the server restarts and the Tile is not loaded when the server restarts the chunk loader will not work.
Second from all my testing they work fine even if moving to other dimensions they work.
The only thing I can think of is that a mod is interfering with the ForgeChunkLoader System

**Comment by Teibidh** [comment]
It is possible that server restarts were the basis of my conclusion, at
least I can't say that they aren't. I will try to test this conclusively.

If I'm understanding you correctly once the server is loaded and a player
enters an area that causes the chunk containing the tile entity to load, it
should be good to go regardless of who is or is not connected until the
server stops?

On Sep 14, 2016 4:39 PM, "Gigabit101" notifications@github.com wrote:

So first of all if the server restarts and the Tile is not loaded when the
server restarts the chunk loader will not work.
Second from all my testing they work fine even if moving to other
dimensions they work.
The only thing I can think of is that a mod is interfering with the
ForgeChunkLoader System

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/gigabit101/SimpleChunkLoader/issues/1#issuecomment-247145921,
or mute the thread

**Comment by gigabit101** [comment]
nope anyone entering the chunk will make that chunkloader work again
